SkillUp.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SkillUp.DAL.Context;
using SkillUp.DAL.UnitOfWorks;
using SkillUp.Entity.Entities;
using SkillUp.Entity.Entities.Settings;
using SkillUp.Entity.ViewModels;
using SkillUp.Service.Services.Abstractions;

namespace SkillUp.Web.Controllers
{
    public class HomeController : Controller
    {
        readonly ICourseService _courseService;
        readonly ICategoryService _categoryService;
        readonly IInstructorService _instructorService;
        readonly IProductService _productService;
        readonly IContactService _contactService;
        readonly IReviewCourseService _reviewCourseService;
        readonly IUnitOfWork _unitOfWork;

        public HomeController(ICourseService courseService, ICategoryService categoryService, IInstructorService instructorService, IProductService productService, IContactService contactService, IReviewCourseService reviewCourseService, IUnitOfWork unitOfWork)
        {
            _courseService = courseService;
            _categoryService = categoryService;
            _instructorService = instructorService;
            _productService = productService;
            _contactService = contactService;
            _reviewCourseService = reviewCourseService;
            _unitOfWork = unitOfWork;
        }

        //Home Page
        public async Task<IActionResult> Index()
        {
            IndexVM indexVM = new IndexVM
            {
                Courses = await _courseService.GetAllCourseAsync(),
                Categories = await _categoryService.GetAllCategoryAsync(),
                Instructors = await _instructorService.GetAllInstructorAsync(),
                Products = await _productService.GetAllProductAsync(),  
                CourseReviews = await _reviewCourseService.GetAllCourseReviewAsync(),
            };
            return View(indexVM);
        }


        //About Page
        public IActionResult About()
        {
            return View();
        }


        //Contact Page Get
        public IActionResult Contact()
        {
            return View();
        }


        //Contact Page Post
        [HttpPost]
        public async Task<IActionResult> Contact(CreateContactVM contactVM)
        {
            await _contactService.CreateContactAsync(contactVM);    
            return RedirectToAction(nameof(Index));
        }


        //Faqs PAge
        public async Task<IActionResult> FAQs()
        {
            var faqs = await _unitOfWork.GetRepository<Faq>().GetAllAsync();  
            return View(faqs);
        }

    }
}

SkillUp.Web/ViewComponents/AboutUsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SkillUp.DAL.Context;

namespace SkillUp.Web.ViewComponents
{
	public class AboutUsViewComponent:ViewComponent
	{
        readonly AppDbContext _context;

        public AboutUsViewComponent(AppDbContext context)
        {
            _context = context;
        }


        //AboutUs Setting
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(_context.Abouts.ToDictionary(s => s.Key, s => s.Value));
        }
    }
}

SkillUp.Web/ViewComponents/ContactInfoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SkillUp.DAL.Context;

namespace SkillUp.Web.ViewComponents
{
    public class ContactInfoViewComponent:ViewComponent
    {
        readonly AppDbContext _context;

        public ContactInfoViewComponent(AppDbContext context)
        {
            _context = context;
        }


        //ContactUs Setting
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(_context.ContactInfos.ToDictionary(s => s.Key, s => s.Value));
        }
    }
}

SkillUp.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "SkillUp-About";
}

<section class="page-title gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <div class="breadcrumbs-wrap">
                    <h1 class="breadcrumb-title">Who We Are?</h1>
                    <nav class="transparent">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="breadcrumb-item active theme-cl" aria-current="page">About Us</li>
                        </ol>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</section>


@await Component.InvokeAsync("AboutUs")

SkillUp.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "SkillUp-Contact";
}

@model CreateContactVM
<section class="page-title gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <div class="breadcrumbs-wrap">
                    <h1 class="breadcrumb-title">Get In Touch</h1>
                    <nav class="transparent">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
                            <li class="breadcrumb-item active theme-cl" aria-current="page">Contact Us</li>
                        </ol>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</section>


<section>
    <div class="container">
        <div class="row align-items-start">
            <div class="col-xl-7 col-lg-6 col-md-12 col-sm-12">
                <form method="post">
                <div class="form-group">
                    <h4>We'd love to here from you</h4>
                    <span>Send a message and we'll responed as soos as possible </span>
                </div>
                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                        <div class="form-group">
                            <label>Name</label>
                            <input asp-for="Name" type="text" class="form-control" placeholder="Name" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                        <div class="form-group">
                            <label>Surname</label>
                            <input asp-for="Surname" type="text" class="form-control" placeholder="Surname" />
                                <span asp-validation-for="Surname" class="text-danger"></span>

                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                        <div class="form-group">
                            <label>Email</label>
                                <input asp-for="Email" type="email" class="form-control" placeholder="example@com" />
                                <span asp-validation-for="Email" class="text-danger"></span>

                        </div>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-12 col-sm-12">
                        <div class="form-group">
                            <label>Phone</label>
                                <input asp-for="PhoneNumber" type="tel" class="form-control" placeholder="+994555506949" />
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>

                        </div>
                    </div>
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Message">Message</label>
                                <input asp-for="Message" type="text" class="form-control" placeholder="Enter Your Message " />
                                <span asp-validation-for="Message" class="text-danger"></span>

                        </div>
                    </div>
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                        <div class="form-group">
                            <button class="btn theme-bg text-white btn-md" type="submit">Send Message</button>
                        </div>
                    </div>
                </div>
                </form>
            </div>

            @await Component.InvokeAsync("ContactInfo")

        </div>
    </div>
</section>

SkillUp.Web/Views/Home/FAQs.cshtml
@{
    ViewData["Title"] = "SkillUp-FAQ's";
}

@model ICollection<Faq>
<section class="page-title gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <div class="breadcrumbs-wrap">
                    <h1 class="breadcrumb-title">FAQ's</h1>
                    <nav class="transparent">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a asp-controller="home" asp-action="index" >Home</a></li>
                            <li class="breadcrumb-item active theme-cl" aria-current="page">faqs</li>
                        </ol>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</section>


<section>
    <div class="container">

        <div class="row justify-content-start">
            <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12">
                <div id="accordionExample" class="accordion">

                    @foreach (var faqs in Model)
                    {
                        <div class="card">
                        <div id="headingOne" class="card-header bg-white shadow-sm border-0">
                            <h6 class="mb-0 accordion_title"><a href="#" data-toggle="collapse" data-target="#@(faqs.Name.Substring(0,5).Replace(" ", ""))" aria-expanded="true" aria-controls="@faqs.Description.Substring(1,10)" class="d-block position-relative text-dark collapsible-link py-2">@faqs.Name</a></h6>
                        </div>
                            <div id="@(faqs.Name.Substring(0,5).Replace(" ", ""))" aria-labelledby="headingOne" data-parent="#accordionExample" class="collapse show">
                            <div class="card-body pl-3 pr-3 pt-0">
                                <p>@faqs.Description</p>
                            </div>
                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<div class="clearfix"></div>