SkillUp.Web/Areas/InstructorPanel/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SkillUp.DAL.Context;
using SkillUp.Entity.Entities.Relations.CourseExtraProperities;
using SkillUp.Entity.Entities;
using SkillUp.Entity.ViewModels;
using SkillUp.Service.Services.Abstractions;
using SkillUp.Service.Helpers;
using Microsoft.AspNetCore.Identity;
using SkillUp.Service.Services.Concretes;

namespace SkillUp.Web.Areas.InstructorPanel.Controllers
{
    [Area("InstructorPanel")]
    public class ProductController : Controller
    {
        readonly ICategoryService _categoryService;
        readonly IProductService _productService;
        readonly AppDbContext _context;
        readonly IWebHostEnvironment _env;
        readonly UserManager<Instructor> _userManager;
        readonly IInstructorService _instructorService;

        public ProductController(ICategoryService categoryService, IProductService productService, AppDbContext context, IWebHostEnvironment env, UserManager<Instructor> userManager, IInstructorService instructorService)
        {
            _categoryService = categoryService;
            _productService = productService;
            _context = context;
            _env = env;
            _userManager = userManager;
            _instructorService = instructorService;
        }


        //My Products
        public async Task<IActionResult> MyProducts()
        {
            string id = _userManager.GetUserId(HttpContext.User);
            var instructor = await _instructorService.GetInstructorById(id);
            return View(instructor);
        }


        //Add New Product Get
        public async Task<IActionResult> AddNewProduct()
        {
            ViewBag.Categories = new SelectList(await _categoryService.GetAllCategoryAsync(), nameof(Category.Id), nameof(Category.Name));
            ViewBag.Instructors = new SelectList(_context.Instructors, nameof(Instructor.Id), nameof(Instructor.Name));

            return View();
        }


        //Add New Product Post
        [HttpPost]
        public async Task<IActionResult> AddNewProduct(CreateProductVM productVM)
        {
            string id = _userManager.GetUserId(HttpContext.User);

            if (productVM.Image != null)
            {
                string result = productVM.Image.CheckValidate("image/", 500);
                if (result.Length > 0)
                {
                    ModelState.AddModelError("Image", result);
                }
            }
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = new SelectList(await _categoryService.GetAllCategoryAsync(), nameof(Category.Id), nameof(Category.Name));
                ViewBag.Instructors = new SelectList(_context.Instructors, nameof(Instructor.Id), nameof(Instructor.Name));
                return View(productVM);
            }
            await _productService.CreateProductAsync(productVM,id);
            return RedirectToAction(nameof(MyProducts));

        }


        //Delete Product
        public async Task<IActionResult> DeleteProduct(int id)
        {
            await _productService.DeleteProductAsync(id);
            return RedirectToAction(nameof(MyProducts));
        }


        //Update Product Get
        public async Task<IActionResult> UpdateProduct(int id)
        {
            ViewBag.Categories = new SelectList(await _categoryService.GetAllCategoryAsync(), nameof(Category.Id), nameof(Category.Name));
            ViewBag.Instructors = new SelectList(_context.Instructors, nameof(Instructor.Id), nameof(Instructor.Name));
            var product = await _productService.UpdateProductById(id);
            return View(product);
        }


        //Update Product Post
        [HttpPost]
        public async Task<IActionResult> UpdateProduct(int id, UpdateProductVM productVM)
        {
            Product product = await _productService.GetProductById(id);
            if (productVM.Image != null)
            {
                string result = productVM.Image.CheckValidate("image/", 500);
                if (result.Length > 0)
                {
                    ModelState.AddModelError("Image", result);
                }
                product.ImageUrl.DeleteFile(_env.WebRootPath, "user/assets/productimg");
                product.ImageUrl = productVM.Image.SaveFile(Path.Combine(_env.WebRootPath, "user", "assets", "productimg"));

            }
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = new SelectList(await _categoryService.GetAllCategoryAsync(), nameof(Category.Id), nameof(Category.Name));
                ViewBag.Instructors = new SelectList(_context.Instructors, nameof(Instructor.Id), nameof(Instructor.Name));
            }
            await _productService.UpdateProductAsync(id, productVM);
            return RedirectToAction(nameof(MyProducts));
        }
    }
}

SkillUp.Web/Areas/Manage/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SkillUp.DAL.Context;
using SkillUp.Entity.Entities;
using SkillUp.Entity.Entities.Relations.CourseExtraProperities;
using SkillUp.Entity.ViewModels;
using SkillUp.Service.Helpers;
using SkillUp.Service.Services.Abstractions;

namespace SkillUp.Web.Areas.Manage.Controllers
{
    [Area("Manage")]
    [Authorize(Roles = "Admin, SuperAdmin")]

    public class ProductController : Controller
    {
        readonly ICategoryService _categoryService;
        readonly IProductService _productService;
        readonly AppDbContext _context;
        readonly IWebHostEnvironment _env;


        public ProductController(ICategoryService categoryService, IProductService productService, AppDbContext context, IWebHostEnvironment env)
        {
            _categoryService = categoryService;
            _productService = productService;
            _context = context;
            _env = env;
        }


        //All Product
        public async Task<IActionResult> ManageProducts(string? query, int page = 1)
        {
            if(query!=null)
            {
                var product = await _productService.GetAllProductAsync();
                var search = product.Where(c => c.Name.ToLower().Trim().Contains(query.ToLower().Trim())).ToList();
                IEnumerable<Product> paginationsearch = search.Skip((page - 1) * 4).Take(4);
                PaginationVM<Product> searchpaginationVM = new PaginationVM<Product>
                {
                    MaxPageCount = (int)Math.Ceiling((decimal)search.Count / 4),
                    CurrentPage = page,
                    Items = paginationsearch,
                    Query = query
                };
                return View(searchpaginationVM);
            }
            var products = await _productService.GetAllProductAsync();
            IEnumerable<Product> pagination = products.Skip((page - 1) * 4).Take(4);
            PaginationVM<Product> paginationVM = new PaginationVM<Product>
            {
                MaxPageCount = (int)Math.Ceiling((decimal)products.Count / 4),
                CurrentPage = page,
                Items = pagination
            };
            return View(paginationVM);   
        }


        //Delete Product
        public async Task<IActionResult> DeleteProduct(int id)
        {
            await _productService.DeleteProductAsync(id);
            return RedirectToAction(nameof(ManageProducts));
        }


        //Update Product Get
        public async Task<IActionResult> UpdateProduct(int id)
        {
            ViewBag.Categories = new SelectList(await _categoryService.GetAllCategoryAsync(), nameof(Category.Id), nameof(Category.Name));
            ViewBag.Instructors = new SelectList(_context.Instructors, nameof(Instructor.Id), nameof(Instructor.Name));
            var product = await _productService.UpdateProductById(id);
            return View(product);
        }


        //Update Product post
        [HttpPost]
        public async Task<IActionResult> UpdateProduct(int id, UpdateProductVM productVM)
        {
            Product product = new Product();
            if (productVM.Image != null)
            {
                string result = productVM.Image.CheckValidate("image/", 500);
                if (result.Length > 0)
                {
                    ModelState.AddModelError("Image", result);
                }
                //product.ImageUrl.DeleteFile(_env.WebRootPath, "user/assets/productimg");
                product.ImageUrl = productVM.Image.SaveFile(Path.Combine(_env.WebRootPath, "user", "assets", "productimg"));

            }
            if (!ModelState.IsValid)
            {
                ViewBag.Categories = new SelectList(await _categoryService.GetAllCategoryAsync(), nameof(Category.Id), nameof(Category.Name));
                ViewBag.Instructors = new SelectList(_context.Instructors, nameof(Instructor.Id), nameof(Instructor.Name));
            }
            await _productService.UpdateProductAsync(id, productVM);
            return RedirectToAction(nameof(ManageProducts));
        }

    }
}

SkillUp.Web/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SkillUp.DAL.Context;
using SkillUp.Entity.Entities;
using SkillUp.Entity.Entities.Relations.ManyToMany;
using SkillUp.Service.Services.Abstractions;
using Stripe;

namespace SkillUp.Web.Controllers
{
    public class PaymentController : Controller
    {
        UserManager<AppUser> _userManager;
        AppDbContext _appDbContext;
        readonly IInstructorService _instructorService;
        readonly IUserService _userService;


        public PaymentController(UserManager<AppUser> userManager, AppDbContext appDbContext, IUserService userService)
        {
            _userManager = userManager;
            _appDbContext = appDbContext;
            _userService = userService;
        }

        //Stripe Paymet 
        public async Task<IActionResult> Payment()
        {
           
            return View();
        }


        //Stripe Charge
        [HttpPost]
        public async Task<IActionResult> Charge(string stripeEmail, string stripeToken, double wallet)
        {
           
            var customers = new CustomerService();
            var chargers = new ChargeService();

            var customer = customers.Create(new CustomerCreateOptions
            {
                Email = stripeEmail,
                Source = stripeToken,
            });

            
           
            var charge = chargers.Create(new ChargeCreateOptions
            {
                Amount = (long) wallet,
                Description = "Add Balance",
                Currency = "usd",
                Customer = customer.Id,
                ReceiptEmail = stripeEmail,
                Metadata = new Dictionary<string, string>()
                {
                    {"OrderId","111" },
                    {"PostCode","LEE111" }
                }

              

            });

            if (charge.Status == "succeeded")
            {
              
                string BalanceTransactionId = charge.BalanceTransactionId;
                string id = _userManager.GetUserId(HttpContext.User) ;
                AppUser user = _appDbContext.AppUsers.FirstOrDefault(x => x.Id == id);
                user.Wallet += charge.Amount;
                _appDbContext.SaveChanges();

                return RedirectToAction("Index", "Home");
            }


            return RedirectToAction("Index","Home");
        }


        //Buy Course
        public async Task<IActionResult> BuyCourse(int id)
        {
            var course = await _appDbContext.Courses.FirstOrDefaultAsync(c => c.Id == id);
            string userid = _userManager.GetUserId(HttpContext.User);
            AppUser user = await _userService.GetUserById(userid);
            if (course.DiscountPrice==0)
            {
                if (user.Wallet >= course.Price * 100)
                {
                    AppUserCourse userCourse = new AppUserCourse
                    {
                        AppUserId = user.Id,
                        CourseId = id,
                        IsSold = true,
                    };

                    user.Wallet = user.Wallet - course.Price * 100;

                    Instructor instructor = await _appDbContext.Instructors.Include(i => i.Courses).FirstOrDefaultAsync(i => i.Id == course.InstructorId);

                    instructor.Wallet = instructor.Wallet + (course.Price * 100) * 0.75;

                    await _appDbContext.AddAsync(userCourse);
                }
                else
                {
                    return RedirectToAction(nameof(Payment));
                }
            }
            else
            {
                    
                if (user.Wallet >= course.DiscountPrice * 100)
                {
                    AppUserCourse userCourse = new AppUserCourse
                    {
                        AppUserId = user.Id,
                        CourseId = id,
                        IsSold = true,
                    };

                    user.Wallet = user.Wallet - course.DiscountPrice * 100;

                    Instructor instructor = await _appDbContext.Instructors.Include(i => i.Courses).FirstOrDefaultAsync(i => i.Id == course.InstructorId);

                    instructor.Wallet = instructor.Wallet + (course.DiscountPrice * 100) * 0.75;

                    await _appDbContext.AddAsync(userCourse);
                }
                else
                {
                    return RedirectToAction(nameof(Payment));
                }
            }
            await _appDbContext.SaveChangesAsync();
            return RedirectToAction("Index" ,"Library");

        }


        //Buy Product
        public async Task<IActionResult> BuyProduct(int id)
        {
            var product = await _appDbContext.Products.FirstOrDefaultAsync(p => p.Id == id);
            string userid = _userManager.GetUserId(HttpContext.User);
            AppUser user = _appDbContext.AppUsers.FirstOrDefault(x => x.Id == userid);
            if (product.DiscountPrice == 0)
            {
                if (user.Wallet >= product.Price*100)
                {
                    AppUserProduct userProduct = new AppUserProduct
                    {
                        AppUserId = user.Id,
                        ProductId = id,
                        IsBuyed = true,
                    };

                    user.Wallet = user.Wallet - product.Price * 100;
                    Instructor instructor = await _appDbContext.Instructors.Include(i => i.Courses).FirstOrDefaultAsync(i => i.Id == product.InstructorId);
                    instructor.Wallet = instructor.Wallet + (product.DiscountPrice * 100) * 0.75;

                    await _appDbContext.AddAsync(userProduct);
                    await _appDbContext.SaveChangesAsync();
                }
                else
                {
                    return RedirectToAction(nameof(Payment));
                }
                
            }
            else
            {
                if (user.Wallet >= product.DiscountPrice *100)
                {
                    AppUserProduct userProduct = new AppUserProduct
                    {
                        AppUserId = user.Id,
                        ProductId = id,
                        IsBuyed = true,
                    };

                    user.Wallet = user.Wallet - product.DiscountPrice * 100;
                    Instructor instructor = await _appDbContext.Instructors.Include(i => i.Courses).FirstOrDefaultAsync(i => i.Id == product.InstructorId);
                    instructor.Wallet = instructor.Wallet + (product.DiscountPrice * 100) * 0.75;
                    await _appDbContext.AddAsync(userProduct);
                    await _appDbContext.SaveChangesAsync();
                }
                else
                {
                    return RedirectToAction(nameof(Payment));

                }
            }

            return RedirectToAction("Product", "Library");

        }
    }
}

SkillUp.Web/Views/Shop/ProductDetail.cshtml
@{
    ViewData["Title"] = "SkillUp-ProductDetail";
}

@model Product

<section class="page-title gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <div class="breadcrumbs-wrap">
                    <h1 class="breadcrumb-title">Product Detail</h1>
                    <nav class="transparent">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
                            <li class="breadcrumb-item active theme-cl" aria-current="page">Product Detail</li>
                        </ol>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</section>


<section class="pr_detail">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <div class="woocommerce single_product quick_view_wrap">

                    <div class="woo-single-images">
                        <div class="feature-style-single">
                            <img src="~/user/assets/productimg/@Model.ImageUrl" width="296px" height="300px" alt="product-book-06">
                        </div>
                    </div>

                    <div class="summary entry-summary">
                        <div class="woo_inner">
                            <h2 class="woo_product_title">
                                <a href="#">@Model.Name</a>
                            </h2>
                            <ul class="woo_info">
                                <li><strong>Category:</strong>
                                    @foreach (var category in Model?.ProductCategories.Where(ctg => ctg.ProductId == Model.Id))
                                    {
                                      <span>@category.Category.Name</span>
                                    }
                                </li>
                            </ul>
                            <div class="woo_price_rate">
                                <div class="woo_price_fix">
                                    <h3 class="mb-0 theme-cl">
                                        @if (Model.DiscountPrice==0)
                                        {
                                            if (Model.Price > 0)
                                            {
                                                <h3 class ="mb-0 theme-cl">$@Model.Price</h3>
                                            }
                                            if (Model.Price == 0)
                                            {
                                                <h3 class="mb-0 theme-cl">Free</h3>
                                            }
                                        }
                                        @if (Model.DiscountPrice>0)
                                        {
                                            <h3 class ="mb-0 theme-cl">$@Model.DiscountPrice</h3>
                                        }
                                    </h3>
                                </div>
                            </div>
                            <div class="woo_short_desc">
                                <p>
                                    @if (Model.Description.Length>40)
                                    {
                                        <span>@Model.Description.Substring(0,40).</span>
                                    }
                                    @if (Model.Description.Length <= 40)
                                    {
                                        <span>@Model.Description.</span>
                                    }
                                </p>
                                 
                            </div>
                            <div class="woo_buttons">
                                     @if (!(Model.AppUserProducts.Any(a => a.AppUser.UserName == User.Identity.Name)))
                                     {
                                        if (User.Identity.IsAuthenticated)
                                        {
                                            <a asp-action="BuyProduct" asp-controller="Payment" asp-route-id="@Model.Id"   class="btn btn-success">Buy Now</a>
                                        
                                        }
                                        else
                                        {
                                          <a asp-action="signin" asp-controller="account"  class="btn btn-success">Buy Now</a>

                                        }

                                     }
                            </div>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</section>


<section class="pt-0">
    <div class="container">

        <div class="row">

            <div class="col-lg-10 col-md-12 col-sm-12">

                <div class="property_block_wrap_header">
                    <ul class="nav nav-tabs customize-tab tabs_creative" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="general-tab" data-toggle="tab" href="#general" role="tab" aria-controls="general" aria-selected="true">Description</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" id="payment-tab" data-toggle="tab" href="#payment" role="tab" aria-controls="payment" aria-selected="false">Extra Detail</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" id="upgrade-tab" data-toggle="tab" href="#upgrade" role="tab" aria-controls="upgrade" aria-selected="false">Reviews</a>
                        </li>

                    </ul>
                </div>

                <div class="tab-content tabs_content_creative" id="myTabContent">

                    <div class="tab-pane fade show active" id="general" role="tabpanel" aria-labelledby="general-tab">
                        <p>
                            @if (Model.Description.Length > 50)
                            {
                                <span>@Model.Description.Substring(0,100)</span>
                            }
                            @if (Model.Description.Length <= 50)
                            {
                                <span>@Model.Description</span>
                            }
                        </p>
                    </div>

                    <div class="tab-pane fade" id="payment" role="tabpanel" aria-labelledby="payment-tab">
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th scope="row">Author: </th>
                                        <td>
                                           <span>@(Model.Instructor.Name + " " + Model.Instructor.Surname)</span>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th scope="row">SKU</th>
                                        <td>#@Model.SKU</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="upgrade" role="tabpanel" aria-labelledby="upgrade-tab">
                        @if (Model.ProductReviews.Count == 0)
                        {
                        <div class="alert alert-success" role="alert">
                            No any reviews yet
                        </div>
                            
                        }
                        else
                        {
                             <div class="list-single-main-item fl-wrap">
                            <div class="list-single-main-item-title fl-wrap">
                                <h3>Course Reviews -  <span> @Model.ProductReviews.Count </span></h3>
                            </div>
                            <div class="reviews-comments-wrap">
                                @foreach (var review in Model.ProductReviews)
                                {
                                    <div class="reviews-comments-item">
                                        <div class="review-comments-avatar">
                                            @if (review.Appuser.ImageUrl != null)
                                            {
                                                <img src="~/user/assets/userimg/@review.Appuser.ImageUrl" class="img-fluid" alt="">
                                            }
                                            else
                                            {
                                                <img src="~/user/assets/userimg/userimage.png" class="img-fluid" alt="">
                                            }
                                        </div>
                                        <div class="reviews-comments-item-text">
                                            <h4><a href="#">@(review.Appuser.Name + " " + review.Appuser.Surname)</a><span class="reviews-comments-item-date"><i class="ti-calendar theme-cl"></i>@review.ReviewDate.ToString("MM/dd/yyyy h:mm tt")</span></h4>
                                            <div class="clearfix"></div>
                                            <p>"@review.ReviewContent"</p>
                                            <div class="pull-left reviews-reaction">
                                            </div>
                                        </div>
                                    </div>
                                } </div>
                           
                        </div>
                   
                        }
                    </div>
                    </div>
                @{
                    CreateProductReviewVM reviewVM = new CreateProductReviewVM();
                    reviewVM.ReviewContent = "";
                    reviewVM.ProductId = Model.Id;
                    reviewVM.Product = Model;
                }
                @if (Model.AppUserProducts.Any(a => a.AppUser.UserName == User.Identity.Name))
                {
                    @await Html.PartialAsync("_ProductReviewPartial", reviewVM, new ViewDataDictionary(ViewData){{"productid" , Model.Id}})
                }
                         
               </div>
             
            </div>

        </div>
    </div>
</section>