SkillUp.Web/Areas/Manage/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SkillUp.Entity.Entities.Relations.CourseExtraProperities;
using SkillUp.Entity.ViewModels;
using SkillUp.Service.Services.Abstractions;

namespace SkillUp.Web.Areas.Manage.Controllers
{
    [Area("Manage")]
    [Authorize(Roles = "Admin, SuperAdmin")]

    public class CategoryController : Controller
    {
        readonly ISubCategoryService _subCategoryService;
        readonly ICategoryService _categoryService;

        public CategoryController(ISubCategoryService subCategoryService, ICategoryService categoryService)
        { 
            _subCategoryService = subCategoryService;
            _categoryService = categoryService;
        }

        //Add New SubCategory Get:

        public async Task<IActionResult> AddNewSubCategory()
        {
            ViewBag.Categories = new SelectList(await _categoryService.GetAllCategoryAsync(), nameof(Category.Id), nameof(Category.Name));
            return View();
        }


        //Add New SubCategory Post
        [HttpPost]
        public async Task<IActionResult> AddNewSubCategory(CreateSubCategoryVM subCategoryVM)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.Categories = new SelectList(await _categoryService.GetAllCategoryAsync(), nameof(Category.Id), nameof(Category.Name));
                return View(subCategoryVM);
            }
            if (subCategoryVM is null) return NotFound();
            await _subCategoryService.CreateSubCategoryAsync(subCategoryVM);
            return RedirectToAction(nameof(AddNewSubCategory));
        }


        //-------------------------------------Category------------------------------------------


        //All Category
        public async Task<IActionResult> CourseCategory()
        {
            var categories = await _categoryService.GetAllCategoryAsync();
            return View(categories);
        }
      

        //Add New Category Get
        public IActionResult AddNewCategory()
        {
            return View();
        }


        //Add New Category Post
        [HttpPost]
        public async Task<IActionResult> AddNewCategory(CreateCategoryVM categoryVM)
        {
            if (!ModelState.IsValid) return View(categoryVM);
            if (categoryVM is null) return NotFound();
            await _categoryService.CreateCategoryAsync(categoryVM);
            return RedirectToAction(nameof(CourseCategory));
        }


        //Delete Category
        public async Task<IActionResult> DeleteCategory(int id)
        {
            await _categoryService.DeleteCategoryAsync(id);
            return RedirectToAction(nameof(CourseCategory));
        }


        //Update Category Get
        public async Task<IActionResult> UpdateCategory(int id)
        {
            var category = await _categoryService.UpdateCategoryById(id);
            return View(category);
        }


        //Update Category Post
        [HttpPost]
        public async Task<IActionResult> UpdateCategory(int id , UpdateCategoryVM categoryVM)
        {
            await _categoryService.UpdateCategoryAsync(id,categoryVM);
            return RedirectToAction(nameof(CourseCategory));
        }


    }
}

SkillUp.Web/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SkillUp.DAL.Context;
using SkillUp.Entity.Entities;
using SkillUp.Entity.Entities.Relations.ManyToMany;
using SkillUp.Entity.ViewModels;
using SkillUp.Service.Services.Abstractions;
using SkillUp.Service.Services.Concretes;
using Stripe;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace SkillUp.Web.Controllers
{
    public class CategoryController : Controller
    {
        readonly ICategoryService _categoryService;
        readonly ICourseService _courseService;
        readonly AppDbContext _context;
        public CategoryController(ICategoryService categoryService, ICourseService courseService, AppDbContext context)
        {
            _categoryService = categoryService;
            _courseService = courseService;
            _context = context;
        }


        //Get All Categories
        public async Task<IActionResult> Index()
        {
            var categories = await _categoryService.GetAllCategoryAsync(); 
            return View(categories);
        }


        //Course With Category
        public async Task<IActionResult> CourseCategory(string query, int? id, int page = 1)
        {
           var courses = await _context.CourseCategories.Where(c=>c.CategoryId == id).Include(c=>c.Course).ThenInclude(ac=>ac.AppUserCourses).ThenInclude(a=>a.AppUser)
           .Include(ctg=>ctg.Category).Include(c=>c.Course).ThenInclude(p=>p.Paragraphs).ThenInclude(l=>l.Lectures).Include(c=>c.Course).ThenInclude(i=>i.Instructor).ToListAsync();

            if (query != null)
            {
                var search = courses.Where(c => c.Course.Name.ToLower().Trim().Contains(query.ToLower().Trim())).ToList();
                IEnumerable<CourseCategory> paginationsearch = search.Skip((page - 1) * 4).Take(4);
                PaginationVM<CourseCategory> searchpaginationVM = new PaginationVM<CourseCategory>
                {
                    MaxPageCount = (int)Math.Ceiling((decimal)search.Count / 2),
                    CurrentPage = page,
                    Items = paginationsearch,
                    Query = query

                };
                return View(searchpaginationVM);
            }
            else
            {
                IEnumerable<CourseCategory> pagination = courses.Skip((page - 1) * 4).Take(4);
                PaginationVM<CourseCategory> paginationVM = new PaginationVM<CourseCategory>
                {
                    MaxPageCount = (int)Math.Ceiling((decimal)courses.Count / 4),
                    CurrentPage = page,
                    Items = pagination
                };
                return View(paginationVM);

            }

        }
    }
}

SkillUp.Web/Controllers/CourseController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SkillUp.DAL.Context;
using SkillUp.Entity.Entities;
using SkillUp.Entity.ViewModels;
using SkillUp.Service.Services.Abstractions;

namespace SkillUp.Web.Controllers
{
    public class CourseController : Controller
    {
        readonly AppDbContext _appDbContext;
        readonly UserManager<AppUser> _userManager;
        readonly ICourseService _courseService;
        readonly IReviewCourseService _reviewcourseService;

        public CourseController(AppDbContext appDbContext, UserManager<AppUser> userManager, IReviewCourseService reviewcourseService, ICourseService courseService)
        {
            _appDbContext = appDbContext;
            _userManager = userManager;
            _reviewcourseService = reviewcourseService;
            _courseService = courseService;
        }

        //Find Courses
        public async Task<IActionResult> FindCourses(string? query ,int page=1)
        {
            if (query!=null)
            {
                var course = await _courseService.GetAllCourseAsync();
                var search = course.Where(c => c.Name.ToLower().Trim().Contains(query.ToLower().Trim())).ToList();
                IEnumerable<Course> paginationsearch = search.Skip((page - 1) * 2).Take(2);
                PaginationVM<Course> searchpaginationVM = new PaginationVM<Course>
                {
                    MaxPageCount = (int)Math.Ceiling((decimal)search.Count / 2),
                    CurrentPage = page,
                    Items = paginationsearch,
                    Query = query   
                    
                };
                return View(searchpaginationVM);
            }
            var courses = await _courseService.GetAllCourseAsync();
            IEnumerable<Course> pagination = courses.Skip((page-1) * 4).Take(4);
            PaginationVM<Course> paginationVM = new PaginationVM<Course>
            {
                MaxPageCount = (int)Math.Ceiling((decimal) courses.Count / 4),
                CurrentPage = page,
                Items = pagination
            };
            return View(paginationVM);
        }

        //CourseDetail Page
        public async Task<IActionResult> CourseDetail(int id)
        {
            var coursedetail =  _appDbContext.Courses.Include(p=>p.Paragraphs).ThenInclude(l=>l.Lectures)
            .Include(cc=>cc.CourseCategories).ThenInclude(ctg=>ctg.Category)
            .Include(a=>a.AppUserCourses).ThenInclude(u=>u.AppUser)
            .Include(i=>i.Instructor).Include(c=>c.CourseReviews).ThenInclude(u=>u.AppUser).FirstOrDefault(x=>x.Id == id);
             coursedetail.ViewCount ++ ;
             _appDbContext.SaveChanges();
             return View(coursedetail);
        }


        //submit Review Post
        [HttpPost]
        public async Task<IActionResult> SubmitReview(CreateCourseReviewVM review)
        {
            string userid =  _userManager.GetUserId(HttpContext.User);
            if (!ModelState.IsValid) return View(review);
             await  _reviewcourseService.CreateReviewAsync(review, userid);
            return RedirectToAction("Index", "Home");
        }

    }
}

SkillUp.Web/Views/Category/CourseCategory.cshtml
@{
    ViewData["Title"] = "SkillUp-FindCourses";
}

@model PaginationVM<CourseCategory>

<section class="page-title">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="breadcrumbs-wrap">
                    <h1 class="breadcrumb-title>All Courses</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb p-0 bg-white">
                            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="breadcrumb-item active theme-cl" aria-current="page">Find Courses with Category</li>
                        </ol>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</section>

<section class="gray">
    <div class="container">
        <div class="row">

            <div class="col-xl-4 col-lg-4 col-md-12 col-sm-12">
                <div class="page-sidebar p-0">
                    <a class="filter_links" data-toggle="collapse" href="#fltbox" role="button" aria-expanded="false" aria-controls="fltbox">Open Advance Filter<i class="fa fa-sliders-h ml-2"></i></a>
                    <div class="collapse" id="fltbox">
                        <div class="sidebar-widgets p-4">
                            <form asp-controller="Category" asp-action="CourseCategory">
                                <div class="form-group">
                                    <div class="input-with-icon">
                                        <input name="query" type="text" class="form-control" placeholder="Search Cources">
                                        <i class="ti-search"></i>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xl-8 col-lg-8 col-md-12 col-sm-12">
                <div class="row justify-content-center">

                    @foreach (var coursecategory in Model.Items)
                    {
                     
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
                            <div class="crs_grid shadow_none brd">
                                <div class="crs_grid_thumb">
                                    <a asp-action="coursedetail" asp-controller="course" asp-route-id="@coursecategory.Course.Id" class="crs_detail_link">
                                        <img src="~/user/assets/courseimg/@coursecategory.Course.ImageUrl" style="width:350px; height:208px" class="img-fluid rounded" alt="" />
                                    </a>
                                    @foreach (var user in coursecategory.Course.AppUserCourses)
                                    {
                                        if (user.IsSold)
                                        {
                                            <div class="crs_video_ico">
                                                <i class="fa fa-play"></i>
                                            </div>
                                        }
                                    }
                                </div>
                                <div class="crs_grid_caption">
                                    <div class="crs_flex">
                                        <div class="crs_fl_first">
                                            <div class="crs_cates">
                                                <span>
                                                    @foreach (var category in coursecategory.Course.CourseCategories.Where(ctg => ctg.CourseId == coursecategory.Course.Id))
                                                    {
                                                        <span>@category.Category.Name</span>
                                                    }
                                                </span>
                                            </div>
                                        </div>
                                        <div class="crs_fl_last">
                                            <div class="crs_price">
                                                <h2>
                                                    <span class="theme-cl">
                                                        @if (coursecategory.Course.DiscountPrice == 0 && coursecategory.Course.Price > 0)
                                                        {
                                                            <span class="currency">$@coursecategory.Course.Price</span>
                                                        }
                                                        @if (coursecategory.Course.Price == 0 && coursecategory.Course.DiscountPrice == 0)
                                                        {
                                                            <span class="currency">Free</span>
                                                        }
                                                        @if (coursecategory.Course.DiscountPrice > 0)
                                                        {
                                                            <span class="currency">$@coursecategory.Course.DiscountPrice</span>
                                                        }
                                                    </span>
                                                </h2>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="crs_title"><h4><a asp-controller="Course" asp-action="CourseDetail" asp-route-id="@coursecategory.Course.Id" class="crs_title_link">@coursecategory.Course.Name</a></h4></div>
                                    <div class="crs_info_detail">
                                        <ul>

                                            <li><i class="fa fa-video text-success"></i><span>@coursecategory.Course.Paragraphs.Sum(x=>x.Lectures.Count) Lectures</span></li>
                                            @{
                                                TimeSpan totalduration = new TimeSpan(0, 0, 0);
                                                @foreach (var paragraphs in coursecategory.Course.Paragraphs)
                                                {
                                                    @foreach (var lectures in paragraphs.Lectures)
                                                    {
                                                        TimeSpan timeSpan = TimeSpan.ParseExact(lectures.Duration.Replace("hr ", ":").Replace("min ", ":").Replace("sec", ""), @"h\:m\:s", null);
                                                        totalduration = totalduration.Add(timeSpan);
                                                    }
                                                }
                                                string duration = string.Format("{0:%h}hr {0:%m}min {0:%s}sec", totalduration);
                                            }
                                            <li><i class="fa fa-clock text-danger"></i><span>@duration</span></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="crs_grid_foot">
                                    <div class="crs_flex">
                                        <div class="crs_fl_first">
                                            <div class="crs_tutor">
                                                <span class=" crs_auth small"> By: <a asp-controller="instructor" asp-action="instructorDetail" asp-route-id="@coursecategory.Course.Instructor.Id">@(coursecategory.Course.Instructor.Name + " " + coursecategory.Course.Instructor.Surname)</a></span>
                                            </div>
                                        </div>
                                        <div class="crs_fl_last">
                                            <div class="foot_list_info">
                                                <ul class="light">
                                                    <li><div class="elsio_ic"><i class="fa fa-user text-danger"></i></div><div class="elsio_tx">@coursecategory.Course.AppUserCourses.Count</div></li>
                                                    <li><div class="elsio_ic"><i class="fa fa-eye text-success"></i></div><div class="elsio_tx">@coursecategory.Course.ViewCount</div></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }

                </div>

                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <ul class="pagination p-center">
                            @if (Model.CurrentPage > 1)
                            {
                                <li class="page-item">
                                    @if (Model.Query != null)
                                    {
                                        <a class="page-link" asp-action="FindCourses" asp-route-page="@(Model.CurrentPage-1)" asp-route-query="@Model.Query" tabindex="-1" aria-label="Previous">
                                            <span class="ti-arrow-left"></span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="page-link" asp-action="FindCourses" asp-route-page="@(Model.CurrentPage-1)" tabindex="-1" aria-label="Previous">
                                            <span class="ti-arrow-left"></span>
                                            <span class="sr-only">Previous</span>
                                        </a>
                                    }
                                </li>
                            }
                            @if (Model.Query != null)
                            {
                                @for (int i = 1; i <= Model.MaxPageCount; i++)
                                {
                                    <li class="page-item @(Model.CurrentPage ==i?" disabled":"")">
                                        <a class="page-link" asp-action="FindCourses" asp-route-page="@i" asp-route-query="@Model.Query" tabindex="-1">@i</a>
                                    </li>
                                }
                            }
                            else
                            {
                                @for (int i = 1; i <= Model.MaxPageCount; i++)
                                {
                                    <li class="page-item @(Model.CurrentPage ==i?" disabled":"")">
                                        <a class="page-link" asp-action="FindCourses" asp-route-page="@i" tabindex="-1">@i</a>
                                    </li>

                                }
                            }
                            @if (Model.CurrentPage < Model.MaxPageCount)
                            {
                                <li class="page-item">
                                    @if (Model.Query != null)
                                    {
                                        <a class="page-link" asp-action="FindCourses" asp-route-page="@(Model.CurrentPage+1)" asp-route-query="@Model.Query" tabindex="-1" aria-label="Next">
                                            <span class="ti-arrow-right"></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    }
                                    else
                                    {
                                        <a class="page-link" asp-action="FindCourses" asp-route-page="@(Model.CurrentPage+1)" tabindex="-1" aria-label="Next">
                                            <span class="ti-arrow-right"></span>
                                            <span class="sr-only">Next</span>
                                        </a>
                                    }
                                </li>
                            }
                        </ul>
                    </div>
                </div>

            </div>

        </div>
    </div>
</section>

SkillUp.Web/Views/Category/Index.cshtml
@{
    ViewData["Title"] = "SkillUp-Category";
}
@model ICollection<Category>
<section class="page-title gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">

                <div class="breadcrumbs-wrap">
                    <h1 class="breadcrumb-title">Explore Category</h1>
                    <nav class="transparent">
                        <ol class="breadcrumb p-0">
                            <li class="breadcrumb-item"><a asp-controller="home" asp-action="index">Home</a></li>
                            <li class="breadcrumb-item active theme-cl" aria-current="page">All Categories</li>
                        </ol>
                    </nav>
                </div>

            </div>
        </div>
    </div>
</section>

<section>
    <div class="container">
        <div class="row justify-content-center">
            @foreach (var category in Model)
            {
                 <div class="col-xl-3 col-lg-4 col-md-4">
                <div class="cates_crs_wrip">
                    <div class="row">
                    <div class="col crs_trios">
                        <div class="crs_cate_icon"><i class="@category.IconUrl"></i></div>
                    </div>
                        <div class="col">
                       <h6 class="text-white">@category.CourseCategories.Count Course</h6>
                        </div>
                        </div>
                    <div class="row crs_capt_cat">
                        <div class="col">
                                <a asp-controller="Category" asp-action="CourseCategory" asp-route-id="@category.Id"><h4>@category.Name</h4> </a>
                        </div>
                    </div>
                        <div class="row crs_capt_cat">
                            <div class="col">
                        <p>@category.Description</p>
                        </div>
                        </div>
                </div>
            </div>
            }
        </div>

        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-12 text-center">
            </div>
        </div>
    </div>
</section>